export const dynamic='force-dynamic';
import Link from 'next/link';import {redirect} from 'next/navigation';import {createAuthClient,supabaseConfigured} from '@/lib/supabase/server';import {services,serviceName,todaySP,formatDateBR,type Booking} from '@/lib/data';import {setBookingStatus,signOut} from './actions';
const whatsapp=(phone:string)=>{const d=phone.replace(/\D/g,'');return `https://wa.me/${d.length<=11?'55'+d:d}`};
export default async function Page(){
 if(!supabaseConfigured())return <main className="page"><div className="empty"><h2>Supabase ainda não configurado.</h2><p>Siga os passos do README para conectar o banco e criar o login da Helaine.</p></div></main>;
 const supabase=await createAuthClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');
 const {data:admin}=await supabase.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();
 if(!admin)return <main className="page"><div className="empty"><h2>Sem acesso ao painel.</h2><p>O usuário {user.email} não está cadastrado como admin.</p><form action={signOut}><button className="btn gold">Sair</button></form></div></main>;
 const today=todaySP();const {data}=await supabase.from('bookings').select('*').gte('date',today).order('date').order('time');const bookings=(data??[]) as Booking[];const active=bookings.filter(b=>b.status!=='Cancelado');const next=active[0];
 return <main className="admin"><aside><div className="admin-brand">♕ <b>Helaine</b><small>TRANÇAS</small></div><nav><a className="active">⌂ Visão geral</a><a>▦ Agenda</a><a>♧ Clientes</a><a>✣ Serviços</a><a>◉ Pagamentos</a><a>▣ Galeria</a><a>▥ Relatórios</a><a>⚙ Configurações</a></nav><Link href="/">← Voltar ao site</Link><form action={signOut}><button className="quick-action">Sair</button></form></aside><section className="admin-main"><div className="admin-header"><div><small>{user.email}</small><h1>Olá, Helaine 👋</h1><p>Aqui está o resumo da agenda.</p></div><div className="avatar">HT</div></div><div className="stats"><div><span>Agendamentos hoje</span><b>{active.filter(b=>b.date===today).length}</b></div><div><span>Serviços cadastrados</span><b>{services.length}</b></div><div><span>Próximo horário</span><b>{next?`${next.date===today?'':formatDateBR(next.date).slice(0,5)+' '}${next.time}`:'—'}</b></div><div><span>Aguardando confirmação</span><b>{active.filter(b=>b.status==='Pendente').length}</b></div></div><div className="admin-grid"><section className="admin-card"><div className="section-head"><h2>Próximos agendamentos</h2><Link className="text-link" href="/agendar">Novo agendamento →</Link></div>{bookings.length===0?<p className="muted">Nenhum agendamento a partir de hoje.</p>:bookings.map(b=><div className="row" key={b.id}><b>{b.time}<small>{formatDateBR(b.date).slice(0,5)}</small></b><span>{b.name}<small>{serviceName(b.service_id)} · <a href={whatsapp(b.phone)} target="_blank" rel="noreferrer">{b.phone}</a>{b.email?` · ${b.email}`:''}</small></span><div className="row-actions"><i className={b.status.toLowerCase()}>{b.status}</i>{b.status==='Pendente'&&<form action={setBookingStatus.bind(null,b.id,'Confirmado')}><button>Confirmar</button></form>}{b.status!=='Cancelado'&&<form action={setBookingStatus.bind(null,b.id,'Cancelado')}><button>Cancelar</button></form>}</div></div>)}</section><section className="admin-card"><h2>Ações rápidas</h2><Link className="quick-action" href="/agendar">＋ Novo agendamento</Link><button className="quick-action">＋ Adicionar cliente</button><button className="quick-action purple">✣ Cadastrar serviço</button><button className="quick-action">▣ Bloquear horário</button></section></div></section></main>}
